CREATE TABLE GEOMETRY_TYPES (
    type TINYINT PRIMARY KEY,
    type_name VARCHAR(25)
);

INSERT INTO GEOMETRY_TYPES VALUES (1, "Point");
INSERT INTO GEOMETRY_TYPES VALUES (2, "Multipoint");
INSERT INTO GEOMETRY_TYPES VALUES (3, "Polyline");
INSERT INTO GEOMETRY_TYPES VALUES (4, "MultiPolyline");
INSERT INTO GEOMETRY_TYPES VALUES (5, "Polygon");
INSERT INTO GEOMETRY_TYPES VALUES (6, "MutliPolygon");
INSERT INTO GEOMETRY_TYPES VALUES (7, "Envelope");
