CREATE TABLE ISO3 (
    code VARCHAR(3) PRIMARY KEY,
    country VARCHAR(52)
);

INSERT INTO ISO3 (code, country) VALUES ("ABW", "Aruba");
INSERT INTO ISO3 (code, country) VALUES ("AFG", "Afghanistan");
INSERT INTO ISO3 (code, country) VALUES ("AGO", "Angola");
INSERT INTO ISO3 (code, country) VALUES ("AIA", "Anguilla");
INSERT INTO ISO3 (code, country) VALUES ("ALA", "Aland Islands");
INSERT INTO ISO3 (code, country) VALUES ("ALB", "Albania");
INSERT INTO ISO3 (code, country) VALUES ("AND", "Andorra");
INSERT INTO ISO3 (code, country) VALUES ("ARE", "United Arab Emirates");
INSERT INTO ISO3 (code, country) VALUES ("ARG", "Argentina");
INSERT INTO ISO3 (code, country) VALUES ("ARM", "Armenia");
INSERT INTO ISO3 (code, country) VALUES ("ASM", "American Samoa");
INSERT INTO ISO3 (code, country) VALUES ("ATA", "Antarctica");
INSERT INTO ISO3 (code, country) VALUES ("ATF", "French Southern Territories");
INSERT INTO ISO3 (code, country) VALUES ("ATG", "Antigua and Barbuda");
INSERT INTO ISO3 (code, country) VALUES ("AUS", "Australia");
INSERT INTO ISO3 (code, country) VALUES ("AUT", "Austria");
INSERT INTO ISO3 (code, country) VALUES ("AZE", "Azerbaijan");
INSERT INTO ISO3 (code, country) VALUES ("BDI", "Burundi");
INSERT INTO ISO3 (code, country) VALUES ("BEL", "Belgium");
INSERT INTO ISO3 (code, country) VALUES ("BEN", "Benin");
INSERT INTO ISO3 (code, country) VALUES ("BES", "Bonaire, Sint Eustatius and Saba");
INSERT INTO ISO3 (code, country) VALUES ("BFA", "Burkina Faso");
INSERT INTO ISO3 (code, country) VALUES ("BGD", "Bangladesh");
INSERT INTO ISO3 (code, country) VALUES ("BGR", "Bulgaria");
INSERT INTO ISO3 (code, country) VALUES ("BHR", "Bahrain");
INSERT INTO ISO3 (code, country) VALUES ("BHS", "Bahamas");
INSERT INTO ISO3 (code, country) VALUES ("BIH", "Bosnia and Herzegovina");
INSERT INTO ISO3 (code, country) VALUES ("BLM", "Saint Barthélemy");
INSERT INTO ISO3 (code, country) VALUES ("BLR", "Belarus");
INSERT INTO ISO3 (code, country) VALUES ("BLZ", "Belize");
INSERT INTO ISO3 (code, country) VALUES ("BMU", "Bermuda");
INSERT INTO ISO3 (code, country) VALUES ("BOL", "Bolivia (Plurinational State of)");
INSERT INTO ISO3 (code, country) VALUES ("BRA", "Brazil");
INSERT INTO ISO3 (code, country) VALUES ("BRB", "Barbados");
INSERT INTO ISO3 (code, country) VALUES ("BRN", "Brunei Darussalam");
INSERT INTO ISO3 (code, country) VALUES ("BTN", "Bhutan");
INSERT INTO ISO3 (code, country) VALUES ("BVT", "Bouvet Island");
INSERT INTO ISO3 (code, country) VALUES ("BWA", "Botswana");
INSERT INTO ISO3 (code, country) VALUES ("CAF", "Central African Republic");
INSERT INTO ISO3 (code, country) VALUES ("CAN", "Canada");
INSERT INTO ISO3 (code, country) VALUES ("CCK", "Cocos (Keeling) Islands");
INSERT INTO ISO3 (code, country) VALUES ("CHE", "Switzerland");
INSERT INTO ISO3 (code, country) VALUES ("CHL", "Chile");
INSERT INTO ISO3 (code, country) VALUES ("CHN", "China");
INSERT INTO ISO3 (code, country) VALUES ("CIV", "Côte d'Ivoire");
INSERT INTO ISO3 (code, country) VALUES ("CMR", "Cameroon");
INSERT INTO ISO3 (code, country) VALUES ("COD", "Congo, Democratic Republic of the");
INSERT INTO ISO3 (code, country) VALUES ("COG", "Congo");
INSERT INTO ISO3 (code, country) VALUES ("COK",  "Cook Islands");
INSERT INTO ISO3 (code, country) VALUES ("COL", "Colombia");
INSERT INTO ISO3 (code, country) VALUES ("COM", "Comoros");
INSERT INTO ISO3 (code, country) VALUES ("CPV", "Cabo Verde");
INSERT INTO ISO3 (code, country) VALUES ("CRI", "Costa Rica");
INSERT INTO ISO3 (code, country) VALUES ("CUB", "Cuba");
INSERT INTO ISO3 (code, country) VALUES ("CUW", "Curaçao");
INSERT INTO ISO3 (code, country) VALUES ("CXR", "Christmas Island");
INSERT INTO ISO3 (code, country) VALUES ("CYM", "Cayman Islands");
INSERT INTO ISO3 (code, country) VALUES ("CYP", "Cyprus");
INSERT INTO ISO3 (code, country) VALUES ("CZE", "Czechia");
INSERT INTO ISO3 (code, country) VALUES ("DEU", "Germany");
INSERT INTO ISO3 (code, country) VALUES ("DJI", "Djibouti");
INSERT INTO ISO3 (code, country) VALUES ("DMA", "Dominica");
INSERT INTO ISO3 (code, country) VALUES ("DNK", "Denmark");
INSERT INTO ISO3 (code, country) VALUES ("DOM", "Dominican Republic");
INSERT INTO ISO3 (code, country) VALUES ("DZA", "Algeria");
INSERT INTO ISO3 (code, country) VALUES ("ECU", "Ecuador");
INSERT INTO ISO3 (code, country) VALUES ("EGY", "Egypt");
INSERT INTO ISO3 (code, country) VALUES ("ERI", "Eritrea");
INSERT INTO ISO3 (code, country) VALUES ("ESH", "Western Sahara");
INSERT INTO ISO3 (code, country) VALUES ("ESP", "Spain");
INSERT INTO ISO3 (code, country) VALUES ("EST", "Estonia");
INSERT INTO ISO3 (code, country) VALUES ("ETH", "Ethiopia");
INSERT INTO ISO3 (code, country) VALUES ("FIN", "Finland");
INSERT INTO ISO3 (code, country) VALUES ("FJI", "Fiji");
INSERT INTO ISO3 (code, country) VALUES ("FLK", "Falkland Islands (Malvinas)");
INSERT INTO ISO3 (code, country) VALUES ("FRA", "France");
INSERT INTO ISO3 (code, country) VALUES ("FRO", "Faroe Islands");
INSERT INTO ISO3 (code, country) VALUES ("FSM", "Micronesia (Federated States of)");
INSERT INTO ISO3 (code, country) VALUES ("GAB", "Gabon");
INSERT INTO ISO3 (code, country) VALUES ("GBR", "United Kingdom of Great Britain and Northern Ireland");
INSERT INTO ISO3 (code, country) VALUES ("GEO", "Georgia");
INSERT INTO ISO3 (code, country) VALUES ("GGY", "Guernsey");
INSERT INTO ISO3 (code, country) VALUES ("GHA", "Ghana");
INSERT INTO ISO3 (code, country) VALUES ("GIB", "Gibraltar");
INSERT INTO ISO3 (code, country) VALUES ("GIN", "Guinea");
INSERT INTO ISO3 (code, country) VALUES ("GLP", "Guadeloupe");
INSERT INTO ISO3 (code, country) VALUES ("GMB", "Gambi");
INSERT INTO ISO3 (code, country) VALUES ("GNB", "Guinea-Bissau");
INSERT INTO ISO3 (code, country) VALUES ("GNQ",  "Equatorial Guinea");
INSERT INTO ISO3 (code, country) VALUES ("GRC", "Greece");
INSERT INTO ISO3 (code, country) VALUES ("GRD", "Grenada");
INSERT INTO ISO3 (code, country) VALUES ("GRL", "Greenland");
INSERT INTO ISO3 (code, country) VALUES ("GTM", "Guatemala");
INSERT INTO ISO3 (code, country) VALUES ("GUF", "French Guiana");
INSERT INTO ISO3 (code, country) VALUES ("GUM", "Guam");
INSERT INTO ISO3 (code, country) VALUES ("GUY", "Guyana");
INSERT INTO ISO3 (code, country) VALUES ("HKG", "Hong Kong");
INSERT INTO ISO3 (code, country) VALUES ("HMD", "Heard Island and McDonald Islands");
INSERT INTO ISO3 (code, country) VALUES ("HND", "Honduras");
INSERT INTO ISO3 (code, country) VALUES ("HRV", "Croatia");
INSERT INTO ISO3 (code, country) VALUES ("HTI", "Haiti");
INSERT INTO ISO3 (code, country) VALUES ("HUN", "Hungary");
INSERT INTO ISO3 (code, country) VALUES ("IDN", "Indonesia");
INSERT INTO ISO3 (code, country) VALUES ("IMN", "Isle of Man");
INSERT INTO ISO3 (code, country) VALUES ("IND", "India");
INSERT INTO ISO3 (code, country) VALUES ("IOT", "British Indian Ocean Territory");
INSERT INTO ISO3 (code, country) VALUES ("IRL", "Ireland",)
INSERT INTO ISO3 (code, country) VALUES ("IRN", "Iran (Islamic Republic of)");
INSERT INTO ISO3 (code, country) VALUES ("IRQ", "Iraq");
INSERT INTO ISO3 (code, country) VALUES ("ISL", "Iceland");
INSERT INTO ISO3 (code, country) VALUES ("ISR", "Israel");
INSERT INTO ISO3 (code, country) VALUES ("ITA", "Italy");
INSERT INTO ISO3 (code, country) VALUES ("JAM", "Jamaica");
INSERT INTO ISO3 (code, country) VALUES ("JEY", "Jersey");
INSERT INTO ISO3 (code, country) VALUES ("JOR", "Jordan");
INSERT INTO ISO3 (code, country) VALUES ("JPN", "Japan");
INSERT INTO ISO3 (code, country) VALUES ("KAZ", "Kazakhstan");
INSERT INTO ISO3 (code, country) VALUES ("KEN", "Kenya");
INSERT INTO ISO3 (code, country) VALUES ("KGZ", "Kyrgyzstan");
INSERT INTO ISO3 (code, country) VALUES ("KHM", "Cambodia");
INSERT INTO ISO3 (code, country) VALUES ("KIR", "Kiribati");
INSERT INTO ISO3 (code, country) VALUES ("KNA", "Saint Kitts and Nevis");
INSERT INTO ISO3 (code, country) VALUES ("KOR", "Korea, Republic of");
INSERT INTO ISO3 (code, country) VALUES ("KWT", "Kuwait");
INSERT INTO ISO3 (code, country) VALUES ("LAO", "Lao People's Democratic Republic");
INSERT INTO ISO3 (code, country) VALUES ("LBN", "Lebanon");
INSERT INTO ISO3 (code, country) VALUES ("LBR", "Liberia");
INSERT INTO ISO3 (code, country) VALUES ("LBY", "Libya");
INSERT INTO ISO3 (code, country) VALUES ("LCA", "Saint Lucia");
INSERT INTO ISO3 (code, country) VALUES ("LIE", "Liechtenstein");
INSERT INTO ISO3 (code, country) VALUES ("LKA", "Sri Lanka");
INSERT INTO ISO3 (code, country) VALUES ("LSO", "Lesotho");
INSERT INTO ISO3 (code, country) VALUES ("LTU", "Lithuania");
INSERT INTO ISO3 (code, country) VALUES ("LUX", "Luxembourg");
INSERT INTO ISO3 (code, country) VALUES ("LVA", "Latvia");
INSERT INTO ISO3 (code, country) VALUES ("MAC", "Macao");
INSERT INTO ISO3 (code, country) VALUES ("MAF", "Saint Martin (French part)");
INSERT INTO ISO3 (code, country) VALUES ("MAR", "Morocco");
INSERT INTO ISO3 (code, country) VALUES ("MCO", "Monaco");
INSERT INTO ISO3 (code, country) VALUES ("MDA", "Moldova, Republic of");
INSERT INTO ISO3 (code, country) VALUES ("MDG", "Madagascar");
INSERT INTO ISO3 (code, country) VALUES ("MDV", "Maldives");
INSERT INTO ISO3 (code, country) VALUES ("MEX", "Mexico");
INSERT INTO ISO3 (code, country) VALUES ("MHL", "Marshall Islands");
INSERT INTO ISO3 (code, country) VALUES ("MKD", "North Macedonia");
INSERT INTO ISO3 (code, country) VALUES ("MLI", "Mali");
INSERT INTO ISO3 (code, country) VALUES ("MLT", "Malta");
INSERT INTO ISO3 (code, country) VALUES ("MMR", "Myanmar");
INSERT INTO ISO3 (code, country) VALUES ("MNE", "Montenegro");
INSERT INTO ISO3 (code, country) VALUES ("MNG", "Mongolia");
INSERT INTO ISO3 (code, country) VALUES ("MNP", "Northern Mariana Islands");
INSERT INTO ISO3 (code, country) VALUES ("MOZ", "Mozambique");
INSERT INTO ISO3 (code, country) VALUES ("MRT", "Mauritania");
INSERT INTO ISO3 (code, country) VALUES ("MSR", "Montserrat");
INSERT INTO ISO3 (code, country) VALUES ("MTQ", "Martinique");
INSERT INTO ISO3 (code, country) VALUES ("MUS", "Mauritius");
INSERT INTO ISO3 (code, country) VALUES ("MWI", "Malawi");
INSERT INTO ISO3 (code, country) VALUES ("MYS", "Malaysia");
INSERT INTO ISO3 (code, country) VALUES ("MYT", "Mayotte");
INSERT INTO ISO3 (code, country) VALUES ("NAM", "Namibia");
INSERT INTO ISO3 (code, country) VALUES ("NCL", "New Caledonia");
INSERT INTO ISO3 (code, country) VALUES ("NER", "Niger");
INSERT INTO ISO3 (code, country) VALUES ("NFK", "Norfolk Island");
INSERT INTO ISO3 (code, country) VALUES ("NGA", "Nigeria");
INSERT INTO ISO3 (code, country) VALUES ("NIC", "Nicaragua");
INSERT INTO ISO3 (code, country) VALUES ("NIU", "Niue");
INSERT INTO ISO3 (code, country) VALUES ("NLD", "Netherlands, Kingdom of the");
INSERT INTO ISO3 (code, country) VALUES ("NOR", "Norway");
INSERT INTO ISO3 (code, country) VALUES ("NPL", "Nepal");
INSERT INTO ISO3 (code, country) VALUES ("NRU", "Nauru");
INSERT INTO ISO3 (code, country) VALUES ("NZL", "New Zealand");
INSERT INTO ISO3 (code, country) VALUES ("OMN", "Oman");
INSERT INTO ISO3 (code, country) VALUES ("PAK", "Pakistan");
INSERT INTO ISO3 (code, country) VALUES ("PAN", "Panama");
INSERT INTO ISO3 (code, country) VALUES ("PCN", "Pitcairn");
INSERT INTO ISO3 (code, country) VALUES ("PER", "Peru");
INSERT INTO ISO3 (code, country) VALUES ("PHL", "Philippines");
INSERT INTO ISO3 (code, country) VALUES ("PLW", "Palau");
INSERT INTO ISO3 (code, country) VALUES ("PNG", "Papua New Guinea");
INSERT INTO ISO3 (code, country) VALUES ("POL", "Poland");
INSERT INTO ISO3 (code, country) VALUES ("PRI", "Puerto Rico");
INSERT INTO ISO3 (code, country) VALUES ("PRK", "Korea (Democratic People's Republic of)");
INSERT INTO ISO3 (code, country) VALUES ("PRT", "Portugal");
INSERT INTO ISO3 (code, country) VALUES ("PRY", "Paraguay");
INSERT INTO ISO3 (code, country) VALUES ("PSE", "Palestine, State of");
INSERT INTO ISO3 (code, country) VALUES ("PYF", "French Polynesia");
INSERT INTO ISO3 (code, country) VALUES ("QAT", "Qatar");
INSERT INTO ISO3 (code, country) VALUES ("REU", "Réunion");
INSERT INTO ISO3 (code, country) VALUES ("ROU", "Romania");
INSERT INTO ISO3 (code, country) VALUES ("RUS", "Russian Federation");
INSERT INTO ISO3 (code, country) VALUES ("RWA", "Rwanda");
INSERT INTO ISO3 (code, country) VALUES ("SAU", "Saudi Arabia");
INSERT INTO ISO3 (code, country) VALUES ("SDN", "Sudan");
INSERT INTO ISO3 (code, country) VALUES ("SEN", "Senegal");
INSERT INTO ISO3 (code, country) VALUES ("SGP", "Singapore");
INSERT INTO ISO3 (code, country) VALUES ("SGS", "South Georgia and the South Sandwich Islands");
INSERT INTO ISO3 (code, country) VALUES ("SHN", "Saint Helena, Ascension and Tristan da Cunha");
INSERT INTO ISO3 (code, country) VALUES ("SJM", "Svalbard and Jan Mayen");
INSERT INTO ISO3 (code, country) VALUES ("SLB", "Solomon Islands");
INSERT INTO ISO3 (code, country) VALUES ("SLE", "Sierra Leone");
INSERT INTO ISO3 (code, country) VALUES ("SLV", "El Salvador");
INSERT INTO ISO3 (code, country) VALUES ("SMR", "San Marino");
INSERT INTO ISO3 (code, country) VALUES ("SOM", "Somalia");
INSERT INTO ISO3 (code, country) VALUES ("SPM", "Saint Pierre and Miquelon");
INSERT INTO ISO3 (code, country) VALUES ("SRB", "Serbia");
INSERT INTO ISO3 (code, country) VALUES ("SSD", "South Sudan");
INSERT INTO ISO3 (code, country) VALUES ("STP", "Sao Tome and Principe");
INSERT INTO ISO3 (code, country) VALUES ("SUR", "Suriname");
INSERT INTO ISO3 (code, country) VALUES ("SVK", "Slovakia");
INSERT INTO ISO3 (code, country) VALUES ("SVN", "Slovenia");
INSERT INTO ISO3 (code, country) VALUES ("SWE", "Sweden");
INSERT INTO ISO3 (code, country) VALUES ("SWZ", "Eswatini");
INSERT INTO ISO3 (code, country) VALUES ("SXM", "Sint Maarten (Dutch part)");
INSERT INTO ISO3 (code, country) VALUES ("SYC", "Seychelles");
INSERT INTO ISO3 (code, country) VALUES ("SYR", "Syrian Arab Republic");
INSERT INTO ISO3 (code, country) VALUES ("TCA", "Turks and Caicos Islands");
INSERT INTO ISO3 (code, country) VALUES ("TCD", "Chad");
INSERT INTO ISO3 (code, country) VALUES ("TGO", "Togo");
INSERT INTO ISO3 (code, country) VALUES ("THA", "Thailand");
INSERT INTO ISO3 (code, country) VALUES ("TJK", "Tajikistan");
INSERT INTO ISO3 (code, country) VALUES ("TKL", "Tokelau");
INSERT INTO ISO3 (code, country) VALUES ("TKM", "Turkmenistan");
INSERT INTO ISO3 (code, country) VALUES ("TLS", "Timor-Leste");
INSERT INTO ISO3 (code, country) VALUES ("TON", "Tonga");
INSERT INTO ISO3 (code, country) VALUES ("TTO", "Trinidad and Tobago");
INSERT INTO ISO3 (code, country) VALUES ("TUN", "Tunisia");
INSERT INTO ISO3 (code, country) VALUES ("TUR", "Türkiye");
INSERT INTO ISO3 (code, country) VALUES ("TUV", "Tuvalu");
INSERT INTO ISO3 (code, country) VALUES ("TWN", "Taiwan, Province of China");
INSERT INTO ISO3 (code, country) VALUES ("TZA", "Tanzania, United Republic of");
INSERT INTO ISO3 (code, country) VALUES ("UGA", "Uganda");
INSERT INTO ISO3 (code, country) VALUES ("UKR", "Ukraine");
INSERT INTO ISO3 (code, country) VALUES ("UMI", "United States Minor Outlying Islands");
INSERT INTO ISO3 (code, country) VALUES ("URY", "Uruguay");
INSERT INTO ISO3 (code, country) VALUES ("USA", "United States of America");
INSERT INTO ISO3 (code, country) VALUES ("UZB", "Uzbekistan");
INSERT INTO ISO3 (code, country) VALUES ("VAT", "Holy See");
INSERT INTO ISO3 (code, country) VALUES ("VCT", "Saint Vincent and the Grenadines");
INSERT INTO ISO3 (code, country) VALUES ("VEN", "Venezuela (Bolivarian Republic of)");
INSERT INTO ISO3 (code, country) VALUES ("VGB", "Virgin Islands (British)");
INSERT INTO ISO3 (code, country) VALUES ("VIR", "Virgin Islands (U.S.)");
INSERT INTO ISO3 (code, country) VALUES ("VNM", "Viet Nam");
INSERT INTO ISO3 (code, country) VALUES ("VUT", "Vanuatu");
INSERT INTO ISO3 (code, country) VALUES ("WLF", "Wallis and Futuna");
INSERT INTO ISO3 (code, country) VALUES ("WSM", "Samoa");
INSERT INTO ISO3 (code, country) VALUES ("YEM", "Yemen");
INSERT INTO ISO3 (code, country) VALUES ("ZAF", "South Africa");
INSERT INTO ISO3 (code, country) VALUES ("ZMB", "Zambia");
INSERT INTO ISO3 (code, country) VALUES ("ZWE", "Zimbabwe");